openapi: 3.0.0
info:
  title: Book API (w/ actions)
  description: API for tracking your books, authors and pub-dates.
  termsOfService: https://app.swaggerhub.com/eula
  contact:
    name: Micheal Higgins
    url: https://smartbear.com
    email: micheal.higgins@smartbear.com
  license:
    name: SmartBear License
    url: http://www.smartbear.com/licenses/2021/LICENSE-2.0.html
  version: 1.1.0
  x-jira-ticket: SNOP-2216
  x-security-approval: required
  x-filters:
    status: Devlopment
    business-unit: Retail
    business-domain: Books and Magazines
servers:
- url: https://swaggerhub.mwhiggins.com/virts/SmartBear_Org/Book/1.1.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Book
  description: Book
- name: SmartBear
  description: SmartBear
paths:
  /book:
    get:
      tags:
      - Book
      description: List the books
      operationId: book_get
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Access token is missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        default:
          description: An un-expected error response occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.book_controller
components:
  schemas:
    ErrorModel:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      description: Default error schema.
    inline_response_200:
      required:
      - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_items'
      example:
        items:
        - author: Robert Heinlein
          title: Time Enough For Love
          pub-date: 12-01-1957
        - author: Robert Heinlein
          title: Time Enough For Love
          pub-date: 12-01-1957
    inline_response_200_items:
      required:
      - author
      - pub-date
      - title
      type: object
      properties:
        title:
          type: string
          example: Time Enough For Love
        author:
          type: string
          example: Robert Heinlein
        pub-date:
          type: string
          example: 12-01-1957
      example:
        author: Robert Heinlein
        title: Time Enough For Love
        pub-date: 12-01-1957
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_bearerAuth

